Return OpenTofu with version in response
eclipse-xpanse/tofu-maker pull request #69
Opened 2024-10-14 11:02 UTC by baixinsui

Related to https://github.com/eclipse-xpanse/xpanse/pull/2034

2024-10-14 12:14 UTC, swaroopar requested changes

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/tofu/maker/models/plan/OpenTofuPlan.java
> +    String openTofuWithVersion;
OpenTofuVersionUsed
The version of the Opentofu binary used to execute scripts

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/tofu/maker/models/response/OpenTofuResult.java
> +    @Schema(description = "OpenTofu with version which executed the command.")
OpenTofuVersionUsed
The version of the Opentofu binary used to execute scripts

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/tofu/maker/models/validation/OpenTofuValidationResult.java
> +    @Schema(description = "OpenTofu with version which executed the command.")
OpenTofuVersionUsed
The version of the Opentofu binary used to execute scripts

2024-10-15 02:01 UTC, Alice1319 commented
LGTM

2024-10-15 02:57 UTC, merged